name: adhan_app
description: تطبيق الأذان
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  adhan: ^2.0.0
  geolocator: ^13.0.1
  http: ^1.2.2
  shared_preferences: ^2.3.0
  flutter_local_notifications: 20.1.0
  timezone: ^0.10.0
  android_intent_plus: ^5.2.0
  sensors_plus: ^6.1.1

flutter:
  uses-material-design: true
